id = "nunjucks"
name = "Nunjucks"
version = "0.0.2"
schema_version = 1
authors = ["Jeff Nelson (https://tidaltheory.io)"]
description = "Nunjucks support"
repository = "https://github.com/stormwarning/zed-nunjucks"

[grammars.nunjucks]
repository = "https://github.com/bobrocke/tree-sitter-nunjucks"
commit = "9a82aadd1d132cdf923da7661da6f48690780388"
