id = "nunjucks"
name = "Nunjucks"
version = "0.0.1"
schema_version = 1
authors = ["Jeff Nelson (https://tidaltheory.io)"]
description = "Nunjucks support"
repository = "https://github.com/stormwarning/zed-nunjucks"

[grammars.nunjucks]
repository = "https://github.com/stormwarning/tree-sitter-nunjucks"
commit = "e0de890e82665d54b923e9b3983db37c5b7fbe38"
