on:
    push:
        tags:
            - "v*"

jobs:
    release:
        name: Release Zed extension
        runs-on: ubuntu-latest
        steps:
            # https://github.com/huacnlee/zed-extension-action
            - uses: huacnlee/zed-extension-action@v2
              with:
                  extension-name: nunjucks
                  # extension-path: extensions/${{ extension-name }}
                  push-to: stormwarning/zed-extensions
              env:
                  # Personal Access Token with `repo` & `workflow` scopes.
                  COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
